### ISSUE TITLE
Identify all the products Boston College provides students to help them secure jobs/internships

### ISSUE THREAD

**Issue by aflies1** [promazo/Gen-2-Consulting-BC-Team-#7]
Create a list of all the services/products that BC offers to students to help them secure internships or jobs. For each product create a description and what the potential benefits and problems are for each. include club offerings as well. Submit your list to be reviewed by (Adam) for review.

**Comment by trevorfoehr** [comment]
https://docs.google.com/document/d/12TgPvDt53DqgmErPmlWhJl2jr5bBEGgF0UGzzzMzbrc/edit
